### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/ucoinj#1]
On unbuntu, i get this error when starting ucoinj-elasticsearch.sh:

```bash 
2016-01-11 12:12:50,331  WARN unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:139)
```

**Comment by blavenie** [comment]
Fixed, by added -Djna.nosys=true  in the java command line, in .SH and .BAT files
